"""finding ai triage verdict

Revision ID: 00eed5c8fcf0
Revises: 68c35a6c1744
Create Date: 2026-10-08 13:39:37.755003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00eed5c8fcf0'
down_revision: Union[str, Sequence[str], None] = '68c35a6c1744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('ai_verdict', sa.String(length=24), nullable=True))
    op.add_column('findings', sa.Column('ai_confidence', sa.String(length=8), nullable=True))
    op.add_column('findings', sa.Column('ai_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'ai_reviewed_at')
    op.drop_column('findings', 'ai_confidence')
    op.drop_column('findings', 'ai_verdict')
    # ### end Alembic commands ###
