"""disclosures

Revision ID: 269bc341b2e6
Revises: 37e032a98310
Create Date: 2026-10-07 13:31:13.934189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '269bc341b2e6'
down_revision: Union[str, Sequence[str], None] = '37e032a98310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disclosures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=500), nullable=False),
    sa.Column('contact_source', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('policy_url', sa.String(length=500), nullable=True),
    sa.Column('deadline_days', sa.Integer(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('advisory_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_disclosures_created_by_id_users')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_disclosures_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_disclosures_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_disclosures_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosures')),
    sa.UniqueConstraint('finding_id', name=op.f('uq_disclosures_finding_id'))
    )
    op.create_index(op.f('ix_disclosures_org_id'), 'disclosures', ['org_id'], unique=False)
    op.create_index(op.f('ix_disclosures_project_id'), 'disclosures', ['project_id'], unique=False)
    op.create_table('disclosure_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('disclosure_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_disclosure_events_created_by_id_users')),
    sa.ForeignKeyConstraint(['disclosure_id'], ['disclosures.id'], name=op.f('fk_disclosure_events_disclosure_id_disclosures'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_disclosure_events_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclosure_events'))
    )
    op.create_index(op.f('ix_disclosure_events_disclosure_id'), 'disclosure_events', ['disclosure_id'], unique=False)
    op.create_index(op.f('ix_disclosure_events_org_id'), 'disclosure_events', ['org_id'], unique=False)
    # ### end Alembic commands ###

    for table in ("disclosures", "disclosure_events"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_isolation ON {table} "
            "USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) "
            "WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disclosure_events_org_id'), table_name='disclosure_events')
    op.drop_index(op.f('ix_disclosure_events_disclosure_id'), table_name='disclosure_events')
    op.drop_table('disclosure_events')
    op.drop_index(op.f('ix_disclosures_project_id'), table_name='disclosures')
    op.drop_index(op.f('ix_disclosures_org_id'), table_name='disclosures')
    op.drop_table('disclosures')
    # ### end Alembic commands ###
