"""repository targets

Revision ID: c2bc933e7cbc
Revises: 60f6e4de22fc
Create Date: 2026-10-08 08:14:42.966423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bc933e7cbc'
down_revision: Union[str, Sequence[str], None] = '60f6e4de22fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('fetch_status', sa.String(length=16), server_default='ready', nullable=False))
    op.add_column('targets', sa.Column('fetch_error', sa.String(length=300), nullable=True))
    op.add_column('targets', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'fetched_at')
    op.drop_column('targets', 'fetch_error')
    op.drop_column('targets', 'fetch_status')
    # ### end Alembic commands ###
