"""finding confidence

Revision ID: 68c35a6c1744
Revises: c2bc933e7cbc
Create Date: 2026-10-08 13:00:18.968387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c35a6c1744'
down_revision: Union[str, Sequence[str], None] = 'c2bc933e7cbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('confidence', sa.Enum('firm', 'tentative', name='confidence', native_enum=False, length=32), server_default='tentative', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'confidence')
    # ### end Alembic commands ###
