"""ai assistance

Revision ID: c29da954df1c
Revises: 269bc341b2e6
Create Date: 2026-10-07 13:52:39.239774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c29da954df1c'
down_revision: Union[str, Sequence[str], None] = '269bc341b2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('injection_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_ai_runs_created_by_id_users')),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_ai_runs_finding_id_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_ai_runs_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs'))
    )
    op.create_index(op.f('ix_ai_runs_finding_id'), 'ai_runs', ['finding_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_org_id'), 'ai_runs', ['org_id'], unique=False)
    op.add_column('findings', sa.Column('remediation', sa.Text(), server_default='', nullable=False))
    op.add_column('organizations', sa.Column('ai_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    op.execute("ALTER TABLE ai_runs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE ai_runs FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY tenant_isolation ON ai_runs "
        "USING (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid) "
        "WITH CHECK (org_id = NULLIF(current_setting('app.org_id', true), '')::uuid)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'ai_enabled')
    op.drop_column('findings', 'remediation')
    op.drop_index(op.f('ix_ai_runs_org_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_finding_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    # ### end Alembic commands ###
