"""finding ai assessment

Revision ID: c0fe6af8dc0f
Revises: 00eed5c8fcf0
Create Date: 2026-10-08 13:58:10.828042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0fe6af8dc0f'
down_revision: Union[str, Sequence[str], None] = '00eed5c8fcf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('ai_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'ai_assessment')
    # ### end Alembic commands ###
